$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        768:{
            items:4
        },
        1024:{
            items:4
        },
        1900: {
            items:6
        }
    }
})